### ISSUE TITLE
Compiling on Ubuntu/gcc failure

### ISSUE THREAD

**Issue by hengestone** [llafuente/flang#1]
Hi there,

Seems like there's a file stringc.h dependency missing on the platform above:

CC       src/libast/ast-mk.o
In file included from src/libast/ast-mk.c:26:0:
./flang/flang.h:51:40: fatal error: stringc.h: No such file or directory

Any ideas?

Thanks!

**Comment by hengestone** [comment]
Never mind, saw your string.c repo :)

**Comment by llafuente** [comment]
Fast solution :)

I started string.c long time ago... and decide it will be useful to have a high level string implementation as fast as possible in the language... (not fast enough ^^)

maybe someday I will reimplement string.c in flang (should be very easy it's very c-ish)

Hope you like the language, I will try to document it a bit... in case some people start wondering...
